def test_run_call_order__error_in_setUp(self):
    events = []
    result = LoggingResult(events)


    class Foo(Test.LoggingTestCase):

        def setUp(self):
            super(Foo, self).setUp()
            raise RuntimeError('raised by Foo.setUp')
    Foo(events).run(result)
    expected = ['startTest', 'setUp', 'addError', 'stopTest']
    self.assertEqual(events, expected)
