def test_run_call_order__failure_in_test(self):
    events = []
    result = LoggingResult(events)


    class Foo(Test.LoggingTestCase):

        def test(self):
            super(Foo, self).test()
            self.fail('raised by Foo.test')
    expected = ['startTest', 'setUp', 'test', 'addFailure', 'tearDown', 'stopTest']
    Foo(events).run(result)
    self.assertEqual(events, expected)
