def test_assert_dict_unicode_error(self):
    with catch_warnings(record=True):
        one = ''.join((chr(i) for i in range(255)))
        with self.assertRaises(self.failureException):
            self.assertDictContainsSubset({'foo': one, }, {'foo': u'\ufffd', })
