@failfast
def addUnexpectedSuccess(self, test):
    'Called when a test was expected to fail, but succeed.'
    self.unexpectedSuccesses.append(test)
