def test_addError(self):


    class Foo(unittest2.TestCase):

        def test_1(self):
            pass
    test = Foo('test_1')
    try:
        raise TypeError()
    except:
        exc_info_tuple = sys.exc_info()
    result = unittest2.TestResult()
    result.startTest(test)
    result.addError(test, exc_info_tuple)
    result.stopTest(test)
    self.assertFalse(result.wasSuccessful())
    self.assertEqual(len(result.errors), 1)
    self.assertEqual(len(result.failures), 0)
    self.assertEqual(result.testsRun, 1)
    self.assertEqual(result.shouldStop, False)
    (test_case, formatted_exc) = result.errors[0]
    self.assertTrue((test_case is test))
    self.assertIsInstance(formatted_exc, str)
