def test_unexpected_success(self):


    class Foo(unittest2.TestCase):

        @unittest2.expectedFailure
        def test_die(self):
            pass
    events = []
    result = LoggingResult(events)
    test = Foo('test_die')
    test.run(result)
    self.assertEqual(events, ['startTest', 'addUnexpectedSuccess', 'stopTest'])
    self.assertFalse(result.failures)
    self.assertEqual(result.unexpectedSuccesses, [test])
    self.assertTrue(result.wasSuccessful())
