{
  Exception exception=new Exception();
  assertEquals(getInitialCause(exception),exception);
}
