def test_failureException__default(self):


    class Foo(unittest2.TestCase):

        def test(self):
            pass
    self.assertTrue((Foo('test').failureException is AssertionError))
