def test_failureException__subclassing__explicit_raise(self):
    events = []
    result = LoggingResult(events)


    class Foo(unittest2.TestCase):

        def test(self):
            raise RuntimeError()
        failureException = RuntimeError
    self.assertTrue((Foo('test').failureException is RuntimeError))
    Foo('test').run(result)
    expected = ['startTest', 'addFailure', 'stopTest']
    self.assertEqual(events, expected)
